### ISSUE TITLE
2022-09-01

### ISSUE THREAD

**Issue by profoundsea25** [profoundsea25/TIL#9]
# 학습 내용
### 업무 관리에 대하여
- 일을 할 때는, 목표를 분명히 한다.
- 그리고 그날 그날 작은 목표를 세우고, 공유한다.
- 개발의 경우, 로컬 테스트 환경을 통일시킬 필요가 있으므로, 내용을 적어서 ReadMe.md 같은 파일로 만들어 공유하자.
- 함께 일을 하게 될 경우, 나눌 수 있는 일은 나누도록 하고, 누가 어떤 일을 하는지를 명확히 하는 것이 좋다.
- 스크럼 같은 자리에서 하는 일을 잘 공유하도록 하고, 고민하다가 막힌다 싶으면 동료들에게 도움을 청하자.
  - 특히 나같은 경우 너무 혼자하려고만 하는 건 아닌지 되돌아보자. 특히 재택이면 더더욱 그렇다.

### Swagger로 깨달은 버전 간 호환성 주의하기
- SpringBoot 2.7.3 + Kotlin은 springfox가 제공하는 swagger가 작동을 안 한다. 
  - baseUrl을 추론할 수 없다, nullPointerException 갖가지 이유로 어떤 버전을 바꾸든 안된다.
- 다행히 SpringDoc에서 제공하는 dependency를 통해 해결하였다.
- 버전 간 충돌이 있음을 주의하자. 무조건 최신이라고 좋은 것만이 아니다. 버그가 있을 수도 있고, 기존 코드가 작동하지 않을 수도 있다.
- 특히 Kotlin + Spring은 레퍼런스가 그렇게 풍부한 것은 아닌 것 같다.

### Kotlin으로 람다식 표현하기
- 정리가 안 된다. 레퍼런스 보면서 했는데 아직도 잘 모르겠다. 자바식 람다 표현 돌려줘 ㅜㅜ To-Do로 남긴다.

# 일기
- 스트레스... 삽질 스트레스가 좀 크다. 일정에 대한 압박도 없지 않았었던 것 같다. 그냥 되는 것이 없다. 뭐 하나 할 때마다 오류가 계속 나온다. 무엇보다 코틀린이 너무 답답한 시기다.
- 가이드 해주시는 승환님이 계셔서 정말 다행이고 감사하다. 아직 다른 사람과 함께 업무를 구성하고 분담하는데 미숙함이 있다는 것을 확실히 깨달았다.
- 테스트코드는 만들 때 그렇게 답답할 수가 없는데, 만들고 활용할 때 그 진가가 드러난다.
  - 아직 테스트 코드가 깔끔하지 않다. 계속 뜯어 고쳐야 할 예정이다. 그럴 욕심이 생긴다.

# To-Do
- [x] 코틀린 문법 공부하기
- [x] 이펙티브 코틀린 공부
- [ ] 테스트 코드 품질 관리하기 (TDD 찾아보면서 리팩터링 하기)
